# ruby encoding: utf-8
User.create(name: "Melissa")
User.create(name: "April")
User.create(name: "Luke")
User.create(name: "Devon")
User.create(name: "Sarah")
User.create(name: Faker::Name.name)
User.create(name: Faker::Name.name)
User.create(name: Faker::Name.name)
User.create(name: Faker::Name.name)
User.create(name: Faker::Name.name)

Celebrity.create(name: "Leonardo", age: 44)
Celebrity.create(name: "Brad", age: 55)
Celebrity.create(name: "Angelina", age: 44)
Celebrity.create(name: "Meryl", age: 70)
Celebrity.create(name: "Bruce", age: 64)

#HOBBIES
Hobbies.create(hobby_name: "3D printing")
Hobbies.create(hobby_name: "About.com")
Hobbies.create(hobby_name: "Acrobatics")
Hobbies.create(hobby_name: "Acting")
Hobbies.create(hobby_name: "Action figure")
Hobbies.create(hobby_name: "Adams Media")
Hobbies.create(hobby_name: "Air sports")
Hobbies.create(hobby_name: "Aircraft spotting")
Hobbies.create(hobby_name: "Airsoft")
Hobbies.create(hobby_name: "Alcester")
Hobbies.create(hobby_name: "Amateur Gardening (magazine)")
Hobbies.create(hobby_name: "Amateur astronomy")
Hobbies.create(hobby_name: "Amateur radio")
Hobbies.create(hobby_name: "American Cryptogram Association")
Hobbies.create(hobby_name: "American football")
Hobbies.create(hobby_name: "Animal fancy")
Hobbies.create(hobby_name: "Animation")
Hobbies.create(hobby_name: "Antiquing")
Hobbies.create(hobby_name: "Antiquities")
Hobbies.create(hobby_name: "Aquascaping")
Hobbies.create(hobby_name: "Arcadia Publishing")
Hobbies.create(hobby_name: "Archery")
Hobbies.create(hobby_name: "Art collecting")
Hobbies.create(hobby_name: "Asheville")
Hobbies.create(hobby_name: "Association football")
Hobbies.create(hobby_name: "Astrological Association of Great Britain")
Hobbies.create(hobby_name: "Astrology")
Hobbies.create(hobby_name: "Astronomy")
Hobbies.create(hobby_name: "Audiophile")
Hobbies.create(hobby_name: "Australian Parkour Association")
Hobbies.create(hobby_name: "Australian rules football")
Hobbies.create(hobby_name: "Auto audiophilia")
Hobbies.create(hobby_name: "Auto racing")
Hobbies.create(hobby_name: "Aviation")
Hobbies.create(hobby_name: "Axe throwing")
Hobbies.create(hobby_name: "BASE jumping")
Hobbies.create(hobby_name: "BBC")
Hobbies.create(hobby_name: "BMX")
Hobbies.create(hobby_name: "Backpacking")
Hobbies.create(hobby_name: "Backpacking (travel)")
Hobbies.create(hobby_name: "Badminton")
Hobbies.create(hobby_name: "Badminton England")
Hobbies.create(hobby_name: "Baking")
Hobbies.create(hobby_name: "Baseball")
Hobbies.create(hobby_name: "Basketball")
Hobbies.create(hobby_name: "Baton twirling")
Hobbies.create(hobby_name: "Beach volleyball")
Hobbies.create(hobby_name: "Beatboxing")
Hobbies.create(hobby_name: "Beekeeping")
Hobbies.create(hobby_name: "Bird watching")
Hobbies.create(hobby_name: "Birdwatching")
Hobbies.create(hobby_name: "Blacksmithing")
Hobbies.create(hobby_name: "Blogging")
Hobbies.create(hobby_name: "Board game")
Hobbies.create(hobby_name: "Board sports")
Hobbies.create(hobby_name: "Boardgame Players Association")
Hobbies.create(hobby_name: "Bodybuilding")
Hobbies.create(hobby_name: "Book collecting")
Hobbies.create(hobby_name: "Book discussion club")
Hobbies.create(hobby_name: "Book restoration")
Hobbies.create(hobby_name: "Bowling")
Hobbies.create(hobby_name: "Boxing")
Hobbies.create(hobby_name: "Brazilian jiu-jitsu")
Hobbies.create(hobby_name: "Breadmaking")
Hobbies.create(hobby_name: "Breakdancing")
Hobbies.create(hobby_name: "British Amateur Rugby League Association")
Hobbies.create(hobby_name: "British Beekeepers' Association")
Hobbies.create(hobby_name: "British Canoe Union")
Hobbies.create(hobby_name: "British Cycling")
Hobbies.create(hobby_name: "British Equestrian Federation")
Hobbies.create(hobby_name: "British Go Association")
Hobbies.create(hobby_name: "British Mountaineering Council")
Hobbies.create(hobby_name: "British Mycological Society")
Hobbies.create(hobby_name: "British Numismatic Society")
Hobbies.create(hobby_name: "British Society of Dowsers")
Hobbies.create(hobby_name: "British Sub-Aqua Club")
Hobbies.create(hobby_name: "Building")
Hobbies.create(hobby_name: "Bus spotting")
Hobbies.create(hobby_name: "Butterfly watching")
Hobbies.create(hobby_name: "CNBC")
Hobbies.create(hobby_name: "CSIRO Publishing")
Hobbies.create(hobby_name: "Cabaret")
Hobbies.create(hobby_name: "Calligraphy")
Hobbies.create(hobby_name: "Cambridge University Press")
Hobbies.create(hobby_name: "Camping")
Hobbies.create(hobby_name: "Canal & River Trust")
Hobbies.create(hobby_name: "Candle making")
Hobbies.create(hobby_name: "Canoeing")
Hobbies.create(hobby_name: "Canyoning")
Hobbies.create(hobby_name: "Capstone Publishers")
Hobbies.create(hobby_name: "Car")
Hobbies.create(hobby_name: "Card games")
Hobbies.create(hobby_name: "Charity shop")
Hobbies.create(hobby_name: "Cheerleading")
Hobbies.create(hobby_name: "Cheesemaking")
Hobbies.create(hobby_name: "Chess")
Hobbies.create(hobby_name: "Chicago Tribune")
Hobbies.create(hobby_name: "Climbing")
Hobbies.create(hobby_name: "Clothing")
Hobbies.create(hobby_name: "Coin collecting")
Hobbies.create(hobby_name: "Collecting")
Hobbies.create(hobby_name: "Color guard (flag spinning)")
Hobbies.create(hobby_name: "Coloring book")
Hobbies.create(hobby_name: "Comic Book Collecting Association")
Hobbies.create(hobby_name: "Comic book collecting")
Hobbies.create(hobby_name: "Competitive dance")
Hobbies.create(hobby_name: "Competitive eating")
Hobbies.create(hobby_name: "Composting")
Hobbies.create(hobby_name: "Computer programming")
Hobbies.create(hobby_name: "Confectionery")
Hobbies.create(hobby_name: "Contract Bridge")
Hobbies.create(hobby_name: "Cooking")
Hobbies.create(hobby_name: "Cosplaying")
Hobbies.create(hobby_name: "Couponing")
Hobbies.create(hobby_name: "Cowles Publishing Company")
Hobbies.create(hobby_name: "Craft")
Hobbies.create(hobby_name: "Creative writing")
Hobbies.create(hobby_name: "Cricket")
Hobbies.create(hobby_name: "Crocheting")
Hobbies.create(hobby_name: "Cross-stitch")
Hobbies.create(hobby_name: "Crossword puzzles")
Hobbies.create(hobby_name: "Crown Publishing Group")
Hobbies.create(hobby_name: "Cryptography")
Hobbies.create(hobby_name: "Cue sports")
Hobbies.create(hobby_name: "Curling")
Hobbies.create(hobby_name: "Cycling")
Hobbies.create(hobby_name: "Daily News (New York)")
Hobbies.create(hobby_name: "Daly City, California")
Hobbies.create(hobby_name: "Dance")
Hobbies.create(hobby_name: "Darts")
Hobbies.create(hobby_name: "David Noonan (game designer)")
Hobbies.create(hobby_name: "Debate")
Hobbies.create(hobby_name: "Deltiology")
Hobbies.create(hobby_name: "Diary")
Hobbies.create(hobby_name: "Die-cast toy")
Hobbies.create(hobby_name: "Digital art")
Hobbies.create(hobby_name: "Digital object identifier")
Hobbies.create(hobby_name: "Disc golf")
Hobbies.create(hobby_name: "Distro-hopping")
Hobbies.create(hobby_name: "Do it yourself")
Hobbies.create(hobby_name: "Dog sport")
Hobbies.create(hobby_name: "Dolls")
Hobbies.create(hobby_name: "Dover Publications")
Hobbies.create(hobby_name: "Dowsing")
Hobbies.create(hobby_name: "Drama")
Hobbies.create(hobby_name: "Drawing")
Hobbies.create(hobby_name: "Driving")
Hobbies.create(hobby_name: "Dungeon Master's Guide")
Hobbies.create(hobby_name: "ESPNcricinfo")
Hobbies.create(hobby_name: "ESports")
Hobbies.create(hobby_name: "Education Scotland")
Hobbies.create(hobby_name: "Electronics")
Hobbies.create(hobby_name: "Element collecting")
Hobbies.create(hobby_name: "Embroidery")
Hobbies.create(hobby_name: "England Netball")
Hobbies.create(hobby_name: "Equestrianism")
Hobbies.create(hobby_name: "Exhibition drill")
Hobbies.create(hobby_name: "Experimenting")
Hobbies.create(hobby_name: "FIDE")
Hobbies.create(hobby_name: "Fact-checking")
Hobbies.create(hobby_name: "Fantasy sport")
Hobbies.create(hobby_name: "Fashion")
Hobbies.create(hobby_name: "Fashion design")
Hobbies.create(hobby_name: "Fencing")
Hobbies.create(hobby_name: "Field hockey")
Hobbies.create(hobby_name: "Figure skating")
Hobbies.create(hobby_name: "Film memorabilia")
Hobbies.create(hobby_name: "Fishing")
Hobbies.create(hobby_name: "Fishkeeping")
Hobbies.create(hobby_name: "Flag football")
Hobbies.create(hobby_name: "Flower")
Hobbies.create(hobby_name: "Flower arranging")
Hobbies.create(hobby_name: "Flying disc")
Hobbies.create(hobby_name: "Focal Press")
Hobbies.create(hobby_name: "Football")
Hobbies.create(hobby_name: "Foraging")
Hobbies.create(hobby_name: "Forbes")
Hobbies.create(hobby_name: "Fossil hunting")
Hobbies.create(hobby_name: "Freestyle Football")
Hobbies.create(hobby_name: "Freestyle football")
Hobbies.create(hobby_name: "Furniture")
Hobbies.create(hobby_name: "Fédération Internationale de Volleyball")
Hobbies.create(hobby_name: "Games")
Hobbies.create(hobby_name: "Gardening")
Hobbies.create(hobby_name: "Genealogy")
Hobbies.create(hobby_name: "Geocaching")
Hobbies.create(hobby_name: "Ghost hunting")
Hobbies.create(hobby_name: "Gingerbread house")
Hobbies.create(hobby_name: "Glassblowing")
Hobbies.create(hobby_name: "Go (game)")
Hobbies.create(hobby_name: "Godding")
Hobbies.create(hobby_name: "Gold prospecting")
Hobbies.create(hobby_name: "Golf")
Hobbies.create(hobby_name: "Gongoozler")
Hobbies.create(hobby_name: "Graffiti")
Hobbies.create(hobby_name: "Graphic design")
Hobbies.create(hobby_name: "Greenwood Publishing Group")
Hobbies.create(hobby_name: "Gunsmithing")
Hobbies.create(hobby_name: "Gymnastics")
Hobbies.create(hobby_name: "Handball")
Hobbies.create(hobby_name: "Harvard Magazine")
Hobbies.create(hobby_name: "Herald Sun")
Hobbies.create(hobby_name: "Herbalism")
Hobbies.create(hobby_name: "Herpetoculture")
Hobbies.create(hobby_name: "Herping")
Hobbies.create(hobby_name: "High-power rocketry")
Hobbies.create(hobby_name: "Hiking")
Hobbies.create(hobby_name: "Hobby")
Hobbies.create(hobby_name: "Hobby horse")
Hobbies.create(hobby_name: "Hoboken, New Jersey")
Hobbies.create(hobby_name: "Home improvement")
Hobbies.create(hobby_name: "Home roasting coffee")
Hobbies.create(hobby_name: "Homebrewing")
Hobbies.create(hobby_name: "Hooping")
Hobbies.create(hobby_name: "Horseback riding")
Hobbies.create(hobby_name: "Huffington Post")
Hobbies.create(hobby_name: "Hula hooping")
Hobbies.create(hobby_name: "Human swimming")
Hobbies.create(hobby_name: "Hunting")
Hobbies.create(hobby_name: "Hydroponics")
Hobbies.create(hobby_name: "IPC Media")
Hobbies.create(hobby_name: "Ice hockey")
Hobbies.create(hobby_name: "Ice skating")
Hobbies.create(hobby_name: "Inline skating")
Hobbies.create(hobby_name: "Insect collecting")
Hobbies.create(hobby_name: "International Cheer Union")
Hobbies.create(hobby_name: "International Federation of Gymnastics")
Hobbies.create(hobby_name: "International Hockey Federation")
Hobbies.create(hobby_name: "International Ice Hockey Federation")
Hobbies.create(hobby_name: "International Shooting Sport Federation")
Hobbies.create(hobby_name: "International Skating Union")
Hobbies.create(hobby_name: "International Standard Book Number")
Hobbies.create(hobby_name: "International Yo-Yo Federation")
Hobbies.create(hobby_name: "Internet meme")
Hobbies.create(hobby_name: "Jewelry making")
Hobbies.create(hobby_name: "Jigsaw puzzles")
Hobbies.create(hobby_name: "Jogging")
Hobbies.create(hobby_name: "John Wiley & Sons")
Hobbies.create(hobby_name: "Jonathan Tweet")
Hobbies.create(hobby_name: "Judo")
Hobbies.create(hobby_name: "Juggling")
Hobbies.create(hobby_name: "Jukskei")
Hobbies.create(hobby_name: "Kabaddi")
Hobbies.create(hobby_name: "Karate")
Hobbies.create(hobby_name: "Kart racing")
Hobbies.create(hobby_name: "Katharine Weymouth")
Hobbies.create(hobby_name: "Kayaking")
Hobbies.create(hobby_name: "Kite")
Hobbies.create(hobby_name: "Kitesurfing")
Hobbies.create(hobby_name: "Knife collecting")
Hobbies.create(hobby_name: "Knife making")
Hobbies.create(hobby_name: "Knife throwing")
Hobbies.create(hobby_name: "Knitting")
Hobbies.create(hobby_name: "Kombucha")
Hobbies.create(hobby_name: "LARP Alliance, Inc.")
Hobbies.create(hobby_name: "LARPing")
Hobbies.create(hobby_name: "Lace")
Hobbies.create(hobby_name: "Lacrosse")
Hobbies.create(hobby_name: "Lapidary")
Hobbies.create(hobby_name: "Laser tag")
Hobbies.create(hobby_name: "Lawn Tennis Association")
Hobbies.create(hobby_name: "Learning")
Hobbies.create(hobby_name: "Leather crafting")
Hobbies.create(hobby_name: "Lego")
Hobbies.create(hobby_name: "Lerner Publishing Group")
Hobbies.create(hobby_name: "Letterboxing (hobby)")
Hobbies.create(hobby_name: "Lock picking")
Hobbies.create(hobby_name: "Longboarding")
Hobbies.create(hobby_name: "Los Angeles Times")
Hobbies.create(hobby_name: "Lotology")
Hobbies.create(hobby_name: "Machining")
Hobbies.create(hobby_name: "Macrame")
Hobbies.create(hobby_name: "Magic (illusion)")
Hobbies.create(hobby_name: "Magnet fishing")
Hobbies.create(hobby_name: "Mahjong")
Hobbies.create(hobby_name: "Makeup")
Hobbies.create(hobby_name: "Marbles")
Hobbies.create(hobby_name: "Marching band")
Hobbies.create(hobby_name: "Martial arts")
Hobbies.create(hobby_name: "Massachusetts Institute of Technology")
Hobbies.create(hobby_name: "Media Wales")
Hobbies.create(hobby_name: "Meditation")
Hobbies.create(hobby_name: "Melbourne")
Hobbies.create(hobby_name: "Meme")
Hobbies.create(hobby_name: "Metal detecting")
Hobbies.create(hobby_name: "Metal detector")
Hobbies.create(hobby_name: "Metalworking")
Hobbies.create(hobby_name: "Meteorology")
Hobbies.create(hobby_name: "Microscopy")
Hobbies.create(hobby_name: "Mineral collecting")
Hobbies.create(hobby_name: "Mineralogical Society of America")
Hobbies.create(hobby_name: "Minneapolis")
Hobbies.create(hobby_name: "Mixed drink")
Hobbies.create(hobby_name: "Model aircraft")
Hobbies.create(hobby_name: "Model building")
Hobbies.create(hobby_name: "Model engineering")
Hobbies.create(hobby_name: "Monte Cook")
Hobbies.create(hobby_name: "Mortimer Zuckerman")
Hobbies.create(hobby_name: "Motor sports")
Hobbies.create(hobby_name: "Mountain biking")
Hobbies.create(hobby_name: "Mountaineering")
Hobbies.create(hobby_name: "Movies")
Hobbies.create(hobby_name: "Mushroom hunting")
Hobbies.create(hobby_name: "Music")
Hobbies.create(hobby_name: "Mycology")
Hobbies.create(hobby_name: "NBC News")
Hobbies.create(hobby_name: "NPR")
Hobbies.create(hobby_name: "National Geographic Society")
Hobbies.create(hobby_name: "National Ice Skating Association")
Hobbies.create(hobby_name: "National Library of Australia")
Hobbies.create(hobby_name: "National Operatic and Dramatic Association")
Hobbies.create(hobby_name: "Needlepoint")
Hobbies.create(hobby_name: "Netball")
Hobbies.create(hobby_name: "New York City")
Hobbies.create(hobby_name: "News Corp Australia")
Hobbies.create(hobby_name: "Newsquest")
Hobbies.create(hobby_name: "Newsweek")
Hobbies.create(hobby_name: "Nordic skating")
Hobbies.create(hobby_name: "Orienteering")
Hobbies.create(hobby_name: "Origami")
Hobbies.create(hobby_name: "Oxford University Press")
Hobbies.create(hobby_name: "Paintball")
Hobbies.create(hobby_name: "Painting")
Hobbies.create(hobby_name: "Palgrave Macmillan")
Hobbies.create(hobby_name: "Parkour")
Hobbies.create(hobby_name: "Penton Media")
Hobbies.create(hobby_name: "Perfume")
Hobbies.create(hobby_name: "Pet adoption")
Hobbies.create(hobby_name: "Philately")
Hobbies.create(hobby_name: "Phillumeny")
Hobbies.create(hobby_name: "Photography")
Hobbies.create(hobby_name: "Podcast")
Hobbies.create(hobby_name: "Poi (performance art)")
Hobbies.create(hobby_name: "Poker")
Hobbies.create(hobby_name: "Polo")
Hobbies.create(hobby_name: "Popular Mechanics")
Hobbies.create(hobby_name: "Pottery")
Hobbies.create(hobby_name: "Powerlifting")
Hobbies.create(hobby_name: "Pressed flower craft")
Hobbies.create(hobby_name: "Psylon Press")
Hobbies.create(hobby_name: "PubMed Central")
Hobbies.create(hobby_name: "PubMed Identifier")
Hobbies.create(hobby_name: "Puzzle")
Hobbies.create(hobby_name: "Quilling")
Hobbies.create(hobby_name: "Quilting")
Hobbies.create(hobby_name: "Quizzes")
Hobbies.create(hobby_name: "Racquetball")
Hobbies.create(hobby_name: "Radio-controlled car")
Hobbies.create(hobby_name: "Rafting")
Hobbies.create(hobby_name: "Rail transport modeling")
Hobbies.create(hobby_name: "Rail transport modelling")
Hobbies.create(hobby_name: "Rappelling")
Hobbies.create(hobby_name: "Rapping")
Hobbies.create(hobby_name: "Reading")
Hobbies.create(hobby_name: "Record collecting")
Hobbies.create(hobby_name: "Refinishing")
Hobbies.create(hobby_name: "Road Cycling")
Hobbies.create(hobby_name: "Robot combat")
Hobbies.create(hobby_name: "Rock balancing")
Hobbies.create(hobby_name: "Rock climbing")
Hobbies.create(hobby_name: "Rock tumbling")
Hobbies.create(hobby_name: "Role-playing game")
Hobbies.create(hobby_name: "Roller derby")
Hobbies.create(hobby_name: "Roller skating")
Hobbies.create(hobby_name: "Rowing")
Hobbies.create(hobby_name: "Rowing (sport)")
Hobbies.create(hobby_name: "Royal Aero Club")
Hobbies.create(hobby_name: "Royal Caledonian Curling Club")
Hobbies.create(hobby_name: "Rugby football")
Hobbies.create(hobby_name: "Rugby league")
Hobbies.create(hobby_name: "Running")
Hobbies.create(hobby_name: "Sailing")
Hobbies.create(hobby_name: "Sand art and play")
Hobbies.create(hobby_name: "Satellite watching")
Hobbies.create(hobby_name: "Scouting")
Hobbies.create(hobby_name: "Scrapbooking")
Hobbies.create(hobby_name: "Scuba diving")
Hobbies.create(hobby_name: "Sculling")
Hobbies.create(hobby_name: "Sculpting")
Hobbies.create(hobby_name: "Sea glass")
Hobbies.create(hobby_name: "Seashell")
Hobbies.create(hobby_name: "Second-language acquisition")
Hobbies.create(hobby_name: "Sewing")
Hobbies.create(hobby_name: "Shoemaking")
Hobbies.create(hobby_name: "Shoes")
Hobbies.create(hobby_name: "Shogi")
Hobbies.create(hobby_name: "Shooting")
Hobbies.create(hobby_name: "Shooting sport")
Hobbies.create(hobby_name: "Shopping")
Hobbies.create(hobby_name: "Shortwave listening")
Hobbies.create(hobby_name: "Singing")
Hobbies.create(hobby_name: "Skateboarding")
Hobbies.create(hobby_name: "Sketch (drawing)")
Hobbies.create(hobby_name: "Skiing")
Hobbies.create(hobby_name: "Skimboarding")
Hobbies.create(hobby_name: "Skip Williams")
Hobbies.create(hobby_name: "Skydiving")
Hobbies.create(hobby_name: "Slacklining")
Hobbies.create(hobby_name: "Slot car racing")
Hobbies.create(hobby_name: "Snowboarding")
Hobbies.create(hobby_name: "Soapmaking")
Hobbies.create(hobby_name: "Soccer")
Hobbies.create(hobby_name: "Social media")
Hobbies.create(hobby_name: "Softball")
Hobbies.create(hobby_name: "South Wales Argus")
Hobbies.create(hobby_name: "Speed skating")
Hobbies.create(hobby_name: "Speedcubing")
Hobbies.create(hobby_name: "Sport stacking")
Hobbies.create(hobby_name: "Sports memorabilia")
Hobbies.create(hobby_name: "Squash (sport)")
Hobbies.create(hobby_name: "Stamp collecting")
Hobbies.create(hobby_name: "Stand-up comedy")
Hobbies.create(hobby_name: "Stanford University")
Hobbies.create(hobby_name: "Stone collecting")
Hobbies.create(hobby_name: "Stone skipping")
Hobbies.create(hobby_name: "Stuffed Animals/Plushies Collecting")
Hobbies.create(hobby_name: "Sun bathing")
Hobbies.create(hobby_name: "Surfing")
Hobbies.create(hobby_name: "Survivalism")
Hobbies.create(hobby_name: "Table football")
Hobbies.create(hobby_name: "Table tennis")
Hobbies.create(hobby_name: "Tabletop game")
Hobbies.create(hobby_name: "Taekwondo")
Hobbies.create(hobby_name: "Tai chi")
Hobbies.create(hobby_name: "Taxidermy")
Hobbies.create(hobby_name: "Tea bag")
Hobbies.create(hobby_name: "Telegraph Media Group")
Hobbies.create(hobby_name: "Telephone card")
Hobbies.create(hobby_name: "Television program")
Hobbies.create(hobby_name: "Tennis")
Hobbies.create(hobby_name: "Tennis polo")
Hobbies.create(hobby_name: "Tether car")
Hobbies.create(hobby_name: "The Atlantic")
Hobbies.create(hobby_name: "The Australian")
Hobbies.create(hobby_name: "The Boston Globe")
Hobbies.create(hobby_name: "The Daily Mail")
Hobbies.create(hobby_name: "The Daily Telegraph")
Hobbies.create(hobby_name: "The Economic Times")
Hobbies.create(hobby_name: "The Economist")
Hobbies.create(hobby_name: "The Free Lance–Star")
Hobbies.create(hobby_name: "The Guardian")
Hobbies.create(hobby_name: "The Herald (Glasgow)")
Hobbies.create(hobby_name: "The Herald and Weekly Times")
Hobbies.create(hobby_name: "The Independent")
Hobbies.create(hobby_name: "The New York Times")
Hobbies.create(hobby_name: "The Philadelphia Inquirer")
Hobbies.create(hobby_name: "The Seattle Times")
Hobbies.create(hobby_name: "The Spokesman-Review")
Hobbies.create(hobby_name: "The State News")
Hobbies.create(hobby_name: "The Times")
Hobbies.create(hobby_name: "The Times Group")
Hobbies.create(hobby_name: "Thomas Register")
Hobbies.create(hobby_name: "Ticket (admission)")
Hobbies.create(hobby_name: "Time (magazine)")
Hobbies.create(hobby_name: "Topiary")
Hobbies.create(hobby_name: "Tour skating")
Hobbies.create(hobby_name: "Toys")
Hobbies.create(hobby_name: "Trading cards")
Hobbies.create(hobby_name: "Trainspotting (hobby)")
Hobbies.create(hobby_name: "Trapshooting")
Hobbies.create(hobby_name: "Travel")
Hobbies.create(hobby_name: "Traveling")
Hobbies.create(hobby_name: "Triathlon")
Hobbies.create(hobby_name: "Tribune Publishing")
Hobbies.create(hobby_name: "Ultimate (sport)")
Hobbies.create(hobby_name: "University of Massachusetts Press")
Hobbies.create(hobby_name: "University of New Mexico")
Hobbies.create(hobby_name: "Urban exploration")
Hobbies.create(hobby_name: "Vacation")
Hobbies.create(hobby_name: "Vegetable farming")
Hobbies.create(hobby_name: "Vehicle restoration")
Hobbies.create(hobby_name: "Vice Magazine")
Hobbies.create(hobby_name: "Video editing")
Hobbies.create(hobby_name: "Video game collecting")
Hobbies.create(hobby_name: "Video game development")
Hobbies.create(hobby_name: "Video gaming")
Hobbies.create(hobby_name: "Videophile")
Hobbies.create(hobby_name: "Vintage cars")
Hobbies.create(hobby_name: "Vintage clothing")
Hobbies.create(hobby_name: "Volleyball")
Hobbies.create(hobby_name: "Volleyball England")
Hobbies.create(hobby_name: "Wales Online")
Hobbies.create(hobby_name: "Walking")
Hobbies.create(hobby_name: "Wall Street Journal")
Hobbies.create(hobby_name: "Washington Post")
Hobbies.create(hobby_name: "Water polo")
Hobbies.create(hobby_name: "Water sports")
Hobbies.create(hobby_name: "Weaving")
Hobbies.create(hobby_name: "Weight training")
Hobbies.create(hobby_name: "Welding")
Hobbies.create(hobby_name: "Whale watching")
Hobbies.create(hobby_name: "Whittling")
Hobbies.create(hobby_name: "Wikipedia")
Hobbies.create(hobby_name: "Wiley Publishing")
Hobbies.create(hobby_name: "Wilsonville, Oregon")
Hobbies.create(hobby_name: "Winemaking")
Hobbies.create(hobby_name: "Wizards of the Coast")
Hobbies.create(hobby_name: "Wood carving")
Hobbies.create(hobby_name: "Woodworking")
Hobbies.create(hobby_name: "World Dance Council")
